import './globals.css';

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const metadata = {
  title: 'Xpensea',
  description: 'Generated by Xyvin',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children} <ToastContainer
        position="top-right"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
      /></body>
    </html>
  )
}
